apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sh
      - -c
      - while true; do sleep 1; done
    imagePullPolicy: IfNotPresent
    name: curlcontainer
  restartPolicy: Always
