apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    component: web
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30005
    prototcol: TCP
  selector:
    app: frontend
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
  labels:
    app: backend
    component: api
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30006
    prototcol: TCP
  selector:
    app: backend
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: backend
    component: api
spec:
  ports:
  - port: 9000
    prototcol: TCP
  selector:
    app: backend
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    component: redis
spec:
  ports:
  - port: 6379
    prototcol: TCP
  selector:
    component: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: php-api-stable-ctrl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        component: api
        tier: stable
    spec:
      containers:
      - name: php-fpm
        image: 'b00gizm/php-api:latest'
        imagePullPolicy: Always
        command: ['php5-fpm', '--nodaemonize']
        ports:
        - containerPort: 9000
      - name: php-nginx
        image: 'b00gizm/php-api:latest'
        imagePullPolicy: Always
        command: ['nginx']
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-stable-ctrl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        component: web
        tier: stable
    spec:
      containers:
      - name: frontend
        image: 'b00gizm/frontend:latest'
        imagePullPolicy: Always
        env:
        - name: API_HOST
          value: '10.245.1.3'
        - name: API_PORT
          value: '30006'
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-canary-ctrl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        component: web
        tier: canary
    spec:
      containers:
      - name: frontend
        image: 'b00gizm/frontend:canary'
        imagePullPolicy: Always
        env:
        - name: API_HOST
          value: '10.245.1.3'
        - name: API_PORT
          value: '30006'
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: php-api-canary-ctrl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        component: api
        tier: canary
    spec:
      containers:
      - name: php-fpm
        image: 'b00gizm/php-api:canary'
        imagePullPolicy: Always
        command: ['php5-fpm', '--nodaemonize']
        ports:
        - containerPort: 9000
      - name: php-nginx
        image: 'b00gizm/php-api:canary'
        imagePullPolicy: Always
        command:
        - nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-ctrl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        component: redis
    spec:
      containers:
      - name: redis
        image: 'redis:3'
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
